const normalizeLegacyCharacterName = (value: string) => value.trim().toLowerCase()

const legacyCharacterTaglineMap = new Map<string, string>([
  ['a-character 1', 'Original Character'],
  ['a-character 2', 'Original Character'],
  ['a-character 3', 'Original Character'],
  ['a-character 4', 'Original Character'],
  ['ahri', 'League of Legends'],
  ['aqua-naked', "KonoSuba: God's Blessing on This Wonderful World!"],
  ['ayaka', 'Genshin Impact'],
  ['blake rwby naked', 'RWBY'],
  ['chloe', 'Life Is Strange'],
  ['fischl', 'Genshin Impact'],
  ['ganyu naked', 'Genshin Impact'],
  ['gwen-naked', 'League of Legends'],
  ['itsuki nakano naked', 'The Quintessential Quintuplets'],
  ['jiblil naked', 'No Game No Life'],
  ['kurumi tokisaki naked', 'Date A Live'],
  ['leah naked', 'Stardew Valley'],
  ['lucy', 'Cyberpunk: Edgerunners'],
  ['marinkitagawa', 'My Dress-Up Darling'],
  ['megumin', "KonoSuba: God's Blessing on This Wonderful World!"],
  ['meru-naked', 'Meru the Succubus'],
  ['misaki tobisawa', 'Date A Live'],
  ['nelliel tu', 'Bleach'],
  ['nobara-naked', 'Jujutsu Kaisen'],
  ['orihime', 'Bleach'],
  ['rias naked', 'High School DxD'],
  ['ryuko matoi naked', 'Kill la Kill'],
  ['sakurajima mai naked', 'Rascal Does Not Dream of Bunny Girl Senpai'],
  ['samus aran', 'Metroid'],
  ['shizukamarikawa-naked', 'Highschool of the Dead'],
  ['shura-kirigakure', 'Blue Exorcist'],
  ['sinonaot', 'Sword Art Online'],
  ['sona', 'League of Legends'],
  ['suguha kiriya naked', 'Sword Art Online'],
  ['super-sonico', 'SoniComi'],
  ['tohka yatogami', 'Date A Live'],
  ['tsunade-naked', 'Naruto'],
  ['weiss schnee vol.7 naked', 'RWBY'],
  ['wiz', "KonoSuba: God's Blessing on This Wonderful World!"],
  ['yoko littner naked', 'Gurren Lagann'],
  ['aqua-konosuba', "KonoSuba: God's Blessing on This Wonderful World!"],
  ['aqua', "KonoSuba: God's Blessing on This Wonderful World!"],
  ['fubuki', 'One-Punch Man'],
  ['ganyu', 'Genshin Impact'],
  ['gwen', 'League of Legends'],
  ['hibana', 'Fire Force'],
  ['hinata', 'Naruto'],
  ['holo', 'Spice and Wolf'],
  ['itsuki nakano', 'The Quintessential Quintuplets'],
  ['jibril', 'No Game No Life'],
  ['katara', 'Avatar: The Last Airbender'],
  ['konan', 'Naruto'],
  ['kukudatekarin', 'Blue Archive'],
  ['kurumi tokisaki', 'Date A Live'],
  ['lain', 'Serial Experiments Lain'],
  ['leah', 'Stardew Valley'],
  ['lupusregina beta', 'Overlord'],
  ['makima', 'Chainsaw Man'],
  ['meru', 'Meru the Succubus'],
  ['nobarakugisaki', 'Jujutsu Kaisen'],
  ['oleana', 'Pokemon Sword and Shield'],
  ['rankalee', 'Macross Frontier'],
  ['rem', 'Re:Zero'],
  ['rias', 'High School DxD'],
  ['rosalina', 'Super Mario'],
  ['ryuko matoi', 'Kill la Kill'],
  ['samsong milkyway', 'Original Character (Virtual Assistant)'],
  ['shizukamarikawa', 'Highschool of the Dead'],
  ['st-louis', 'Azur Lane'],
  ['suguha kiriya', 'Sword Art Online'],
  ['suzumura alisa', 'Katainaka ni Totsui de Kita Russia Musume to H Shimakuru Ohanashi'],
  ['tohsaka rin', 'Fate/stay night'],
  ['weiss', 'RWBY'],
  ['yoko littner', 'Gurren Lagann'],
  ['yu-takeyama', 'My Hero Academia'],
  ['yor', 'Spy x Family'],
  ['yukino', 'My Teen Romantic Comedy SNAFU'],
  ['chocola nekopara', 'Nekopara'],
  ['tifa', 'Final Fantasy VII'],
  ['noelle silva', 'Black Clover'],
  ['nicoledemara', 'Zenless Zone Zero'],
  ['mata hari', 'Fate/Grand Order'],
  ['yotsuba', 'The Quintessential Quintuplets'],
  ['alice zuberg', 'Sword Art Online: Alicization'],
  ['washu', 'Tenchi Muyo!'],
  ['alisa mikhailovna', 'Alya Sometimes Hides Her Feelings in Russian'],
  ['grace howard', 'Zenless Zone Zero'],
  ['janedoe', 'Zenless Zone Zero'],
  ['shogun raiden', 'Genshin Impact'],
  ['iria', 'Iria: Zeiram the Animation'],
  ['burnice', 'Zenless Zone Zero'],
  ['tamamo', 'Monster Girl Quest'],
  ['nagatoro', "Don't Toy with Me, Miss Nagatoro"],
  ['nino nakano', 'The Quintessential Quintuplets'],
  ['seras victoria', 'Hellsing'],
  ['filian', 'VTuber'],
  ['shahar shamsiel', 'Kyonyuu Fantasy'],
  ['cha hae', 'Solo Leveling'],
  ['momo ayase', 'Dandadan'],
  ['shylily', 'VTuber'],
  ['android18', 'Dragon Ball'],
  ['meiko shiraki', 'Prison School'],
  ['esdeath', 'Akame ga Kill!'],
  ['mita', 'MiSide'],
  ['aliceliese', 'Our Last Crusade or the Rise of a New World'],
  ['mayumi', 'The Irregular at Magic High School'],
  ['koneko', 'High School DxD'],
  ['rory', 'GATE'],
  ['2b', 'NieR:Automata'],
  ['junko', 'Desert Punk'],
  ['lucoa', "Miss Kobayashi's Dragon Maid"],
  ['marcille', 'Delicious in Dungeon'],
  ['vermeil', 'Vermeil in Gold'],
  ['makina', 'Deadman Wonderland'],
  ['airi', 'Oni Chichi'],
  ['amo', 'Gachiakuta'],
  ['kara', 'Original Character'],
  ['pyrah', 'Xenoblade Chronicles 2'],
  ['delta', 'The Eminence in Shadow'],
  ['alicia', 'Valkyria Chronicles'],
  ['lewis', "Girls' Frontline 2: Exilium"],
  ['suzune', 'Classroom of the Elite'],
  ['sena', 'Xenoblade Chronicles 3'],
  ['frieren', "Frieren: Beyond Journey's End"],
  ['yourichi', 'Bleach'],
  ['lady dimitrescu', 'Resident Evil Village']
])

const getLegacyCharacterTagline = (name: string) => {
  return legacyCharacterTaglineMap.get(normalizeLegacyCharacterName(name)) ?? null
}

export { getLegacyCharacterTagline, legacyCharacterTaglineMap, normalizeLegacyCharacterName }
