const REGISTERED_CHARACTER_SIGN_UP_HREF = 'https://secretwaifu.com/?openSignUp=1'
const EMAIL_VERIFICATION_PROFILE_HREF = '/profile'

export { EMAIL_VERIFICATION_PROFILE_HREF, REGISTERED_CHARACTER_SIGN_UP_HREF }
